include(`bpmn.m4')
start([[Start]])
t(task1, [[Task 1]])
g_xor(xor1, [[Either/Or]])
g_or(or1, [[Some]])
g_and(and1, [[All]])
end([[End]])
to(START_NODE, task1)
to(task1, xor1)
g_to(xor1, or1, [[Option A]])
g_to(xor1, and1, [[Option B]])
to(or1, end__NODE)
to(and1, END_NODE)
